@startuml

left to right direction
package DefesaCivil {
    usecase "Acessar estoque" as acessarEstoque
    usecase "Cadastrar suprimento" as cadastrarSuprimento
    usecase "Enviar mensagem" as mensagem
    usecase "Receber alerta" as receberAlerta
    usecase "Registrar emergencia" as registrarEmergencia
    usecase "Fazer logoff" as fazerLogoff
    usecase "Fazer login" as fazerLogin
    usecase "Manter cadastro" as manterCadastro
}

:MembroEquipe: --> fazerLogin
:MembroEquipe: --> fazerLogoff
:MembroEquipe: --> receberAlerta
:MembroEquipe: --> acessarEstoque
:MembroEquipe: --> mensagem

registrarEmergencia <-- :MembroComando: 
fazerLogin <-- :MembroComando: 
fazerLogoff <-- :MembroComando: 
acessarEstoque <-- :MembroComando: 
cadastrarSuprimento <-- :MembroComando: 
manterCadastro <-- :MembroComando: 
mensagem <-- :MembroComando: 

@enduml
